# Generated by Django 4.2.3 on 2023-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisement_delete_advertisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(default=False, verbose_name='Auction'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(help_text='Field for product name', max_length=100, verbose_name='Name'),
        ),
    ]
